### ISSUE TITLE
Crash on loading mp3 file or folder

### ISSUE THREAD

**Issue by hansluk** [nilennoct/NeoID3#2]
I have installed `taglib` 1.9.1 and `uchardet` 0.0.1.  Should I provide anything to help figuring out why?
on OSX 10.9.5.
Thanks!

**Comment by nilennoct** [comment]
If only you want to build the project in Xcode, you should install `taglib` & `uchardet`. If the app crashed in using, could you upload the mp3 file you used anywhere?
